### ISSUE TITLE
Site background is no longer black but white instead.

### ISSUE THREAD

**Issue by jason-lopez-n** [cicerakes/DarkNight-MyAnimeList#10]
- **Browser:** Chrome Latest version
- **Link to page where the issue occurs:** https://myanimelist.net/

**Describe the problem**
The page background is not white instead of black. I have my Windows on Dark mode by default.

**Screenshots:**
![image](https://user-images.githubusercontent.com/10891866/164863010-79973532-254b-4e17-84c1-b0193d125fcf.png)

**Comment by cicerakes** [comment]
Are you using an ad blocking extension? If so, please see [#9](https://github.com/cicerakes/DarkNight-MyAnimeList/issues/9#issuecomment-1106607757) for possible solutions.

**Comment by jason-lopez-n** [comment]
@cicerakes I applied suggestions on that issue. It is now working fine for me. Thank you.
