### ISSUE TITLE
Background is White when Used with uBlock Origin

### ISSUE THREAD

**Issue by kent-h** [cicerakes/DarkNight-MyAnimeList#11]
**Browser** 
Firefox

**Link to page where the issue occurs** 
Main page, every anime page (probably others)
* https://myanimelist.net
* https://myanimelist.net/anime/355/Shakugan_no_Shana

**Describe the problem**
Sidebars do not seem to be recolored if used with a recent version of uBlock Origin.

I have tried with default settings & with add-hiding enabled/disabled.
(Using this style only does not hide all adds.)

This worked up until about two weeks ago; I assume uBlock pushed an update that broke it.

**Screenshots**
![image](https://user-images.githubusercontent.com/8741399/165655239-178431d2-a691-4c5c-a450-8a0d1acf673b.png)
![image](https://user-images.githubusercontent.com/8741399/165655488-198faecc-be6d-4593-9495-cecea51c1926.png)

**Comment by along02** [comment]
Some solutions are here. https://github.com/cicerakes/DarkNight-MyAnimeList/issues/9

**Comment by kent-h** [comment]
So I'm not the first one then 😅

This solution in particular worked for me:
https://github.com/cicerakes/DarkNight-MyAnimeList/issues/9#issuecomment-1106607757

Thanks ;)
