### ISSUE TITLE
New "quick reply" div has a white background

### ISSUE THREAD

**Issue by Exablade** [cicerakes/DarkNight-MyAnimeList#12]
- **Browser:** Firefox 102.0.1
- **Link to page where the issue occurs:** Any forum thread https://myanimelist.net/forum/

**Describe the problem**
This is the css rule that makes it white:
```
.page-common .topic-bottom-reply {
	background-color: #f6f6f6;
}
```
I'll let you decide what color works best.

**Screenshots:**
This doesn't seem necessary.

**Comment by Exablade** [comment]
I feel like an idiot, I just noticed the "Contributing" part in the readme. I followed what the table was saying and I ended up with this:
```
.page-common .topic-bottom-reply {
	background-color: #272727;
}
.page-common .topic-bottom-reply::before {
	border-bottom: 12px solid #272727;
}
.page-common .btn-topic-normal.inverse {
	color: #5378cb;
}
```
Forgive me if this isn't the proper to do this, I'm not familiar with how the pull request system works.

**Comment by cicerakes** [comment]
[GitHub has docs on making pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) if you'd like to learn :)  
A quick summary is that you'll need to fork this repo, make changes, then make a pull request.

Either way, thanks for posting your code!
