### ISSUE TITLE
Content bars containing sort options on the people pages are white.

### ISSUE THREAD

**Issue by Chiribei** [cicerakes/DarkNight-MyAnimeList#6]
- **Browser:** Firefox
- **Link to page where the issue occurs:** https://myanimelist.net/people/185/Kana_Hanazawa

**Describe the problem**
The content bars present on the people pages in voice acting roles, anime staff positions and published manga that contain the sort option along with the ability to make sure that only anime/manga on your list are displayed in white. It's a relatively new feature on the site, so I'm not surprised it hasn't been accounted for yet, but I thought I'd report it as an issue to see if a fix for it is possible.

**Screenshots:**

![Screenshot 2022-01-17 023656(1)](https://user-images.githubusercontent.com/84291506/149673453-18ae841f-f591-4af0-ad05-b390a548a017.png)
![Screenshot 2022-01-17 023730](https://user-images.githubusercontent.com/84291506/149673360-7f463579-2402-4a8a-ba8d-40c4ee496710.png)
![Screenshot 2022-01-17 023744](https://user-images.githubusercontent.com/84291506/149673365-777c18af-4a43-483f-899e-d61f9c406060.png)

**Comment by BriterNC** [comment]
This also occurred on Chrome browser.
Adding these line to code 1 section (for Stylish user, cuz I'm using it) solved the problem on my Chrome browser.
(I have tested on Firefox, it also worked.):
> .people-character {
    background-color: #1e1e1e;
    border-bottom: #3e3e3e 1px solid;
}
.people-staff {
    background-color: #1e1e1e;
    border-bottom: #3e3e3e 1px solid;
}
.people-manga {
    background-color: #1e1e1e;
    border-bottom: #3e3e3e 1px solid;
}

**Screenshots:**
Before:
![Untitled-1](https://user-images.githubusercontent.com/27994735/149723110-4d03eb9e-2d40-4857-893b-f4fca6d32543.png)
After:
![Untitled-2](https://user-images.githubusercontent.com/27994735/149723135-a944b526-38a2-4cf3-a09a-61c8be57927a.png)

**Comment by Chiribei** [comment]
Awesome. Thanks.
