### ISSUE TITLE
White borders

### ISSUE THREAD

**Issue by along02** [cicerakes/DarkNight-MyAnimeList#9]
- **Browser:** 
- Chrome
- **Link to page where the issue occurs:** 
https://myanimelist.net/
(any page)
**Describe the problem**
The sides are white rather than black. 

**Screenshots:**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/21041802/162876167-9bb0fc0d-fd31-4965-a9ac-0133bb7312b9.png)

**Comment by cicerakes** [comment]
I am currently unable to reproduce this after checking multiple pages. 

Is it possible that you have another theme/style installed which is causing this?

**Comment by along02** [comment]
Yeah, sorry. I updated my ublock and it fixed it.

**Comment by along02** [comment]
Sorry, it seems like the problem is back. The style breaks when you incorporate it with an adblocker like ublock or Adguard.

**Comment by cicerakes** [comment]
I am using uBlock Origin along with this and don't have this issue. 

Does disabling just uBlock or just Adguard fix it?

**Comment by along02** [comment]
Yeah, I updated my filter list and it broke again. Disabling both of them fixes it. Having either one on (or both) breaks it still.

**Comment by cicerakes** [comment]
Without being able to replicate it right now, I'm guessing the adblock is forcing a white background after it removes ads, overwriting the dark background applied by the theme. 

Could you send me a screenshot of your filter lists in uBlock? I'd like to try them out and see if I can reproduce the problem.  
You can find them in uBlock Dashboard (wheel cogs icon) > Filter lists.

**Comment by along02** [comment]
![image](https://user-images.githubusercontent.com/21041802/164608450-6a9f6b4c-9130-487a-88c5-3619edc051de.png)

**Comment by cicerakes** [comment]
In the uBlock dashboard, go to the "My filters" section, then add this bit of code as a new line and then click on "Apply changes": 
`myanimelist.net##body:not(.ownlist):style(background: #1e1e1e !important)`

Refresh MAL and let me know if this helps with the problem.

**Comment by along02** [comment]
Yup, fixed it. Thanks!

**Comment by KiitoX** [comment]
I found this was not working reliably, but adding this line to "My rules" did it for me:
```no-cosmetic-filtering: myanimelist.net true```

It's also possible to toggle this setting on/off from the pop-up with a button as shown here: https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-cosmetic-filtering

The button also shows how many rules were applied to the site (as of today, for me it was just one on MAL)

**Comment by clem193** [comment]
Cause of this issue :
https://github.com/uBlockOrigin/uAssets/issues/12854

**Comment by Exablade** [comment]
> In the uBlock dashboard, go to the "My filters" section, then add this bit of code as a new line and then click on "Apply changes": `myanimelist.net##body:not(.ownlist):style(background: #1e1e1e !important)`
> 
> Refresh MAL and let me know if this helps with the problem.

This didn't work for me but `myanimelist.net##body.page-common:not(.ownlist):style(background: #1e1e1e !important)` did (something about rule specificity).

**Comment by krystian3w** [comment]
Yeah css specificity enforce run:

`nimelist.net##body.page-common:not(.ownlist):style(background: #1e1e1e !important)`

![obraz](https://user-images.githubusercontent.com/35370833/164991838-6054374c-add0-4a2f-b5c1-1b73c4482641.png)

021 is higher than 011
